# Generated by Django 4.2.19 on 2025-02-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_news_alter_car_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
